version: '2'
services:
    etl:
        build: ./etl/
        volumes:
            - ./etl:/etl
        depends_on:
            - redis
    web:
        build: ./app/
        ports:
            - "5000:5000"
        volumes:
            - ./app:/app
        depends_on:
            - etl
    redis:
        image: redis
